### ISSUE TITLE
Certificate revocation list

### ISSUE THREAD

**Issue by slashbeast** [nothinux/octo-proxy#19]
Hi,

I am looking into octo-proxy and so far it looks great!

One thing that come to me while looking at it is that it appears to have no interface for certificate revocation list. With service being exposed and using mTLS as the authorization and authentication layer of clients, it would a lot of sense to provide a way to revoke/close access to a client that have valid (not expired) certificate issued by the CA that both ends trusted.

Would that be something you'd consider adding?

**Comment by nothinux** [comment]
Hi @slashbeast 

Thanks for checking out octo-proxy!

I'll dig into this to see if we can enhance the validation and check the certificate against the CRL. In the meantime, I'm curious about your use case. Could you share it?

**Comment by slashbeast** [comment]
I am evaluating mTLS as alternative to VPN for unattended system services communication over the public internet, since in a matter of fact it provides very similar level of security like say OpenVPN that also uses TLS, but without all the network level hackery. that you need to build and maintain on each end.

In that case I might have a service exposed to internet to which I generate certificates, multiple clients, and for the sake of secrets rotation, I will want to revoke the old certificates, however changing whole CA every time would introduce a downtime or a very problematic maintenance model.

I think the OpenVPN's flow of it is pretty good, or at the very least could help explain what kind of functionality I am looking for -- https://openvpn.net/community-resources/revoking-certificates/

**Comment by nothinux** [comment]
Thanks for sharing your use case, The CRL feature has been merged into the main branch. You can try it by building the octo-proxy binary yourself, or you can wait until version 1.2.0 is released.

For setting up CRL you can refer to the [docs](https://github.com/nothinux/octo-proxy/blob/main/docs/CONFIGURATION.md#tlsconfig)

**Comment by fff7d1bc** [comment]
Thanks! I will play around with it somewhere during the weekend.
